
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/hybolic/Meadery/issues"
[[mods]]
modId="meadery"
version="0.2.1"
displayName="Meadery Mod"
updateJSONURL="https://raw.githubusercontent.com/hybolic/Meadery/master/BUILDS/versions.json"
displayURL="https://github.com/hybolic/Meadery/"
logoFile="meadery.png"
credits=""
authors="nadir"
description='''
'''